In [98]:
# Import dependancies
import numpy as np
import statistics


from sklearn import metrics
from sklearn.datasets import load_digits
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import confusion_matrix

In [99]:
#import datasets
digits = load_digits()

In [100]:
# flatten the images
n_samples = len(digits.images)

data = digits.images.reshape((n_samples, -1))

In [101]:
#x is feature vector and y is true labels
x = data
y = digits.target

In [102]:
# 10 number of clusters are given as input to agglomerative clustering
n_clusters = 10 

# Input number of clusters and ward linkage method inside agglomerativeclustering function
ward = AgglomerativeClustering(
    n_clusters=n_clusters, linkage="ward"
)

In [103]:
#Fitting and predicting the clusters
ward.fit_predict(x)

array([7, 9, 4, ..., 4, 1, 4], dtype=int64)

In [104]:
#Check the cluster and see which true label value frequency is highest inside cluster
assigned_label = ward.labels_
true_label = digits.target

temp = []
mat = []
corrected_label = []
for i in range(10):
    for j in range(n_samples):
        if assigned_label[j] == i:
            temp.append(true_label[j])
            mode = statistics.mode(temp)
    corrected_label.append(mode)
    mat = temp
    temp.clear()

print("Most frequent labels of 10 clusters:",corrected_label)

Most frequent labels of 10 clusters: [5, 3, 2, 7, 8, 4, 6, 0, 1, 1]


Only 9 labels are most occuring in 10 clusters found by agglomerative method. Cluster number 9 is not identified.

In [105]:
# Assign most frequent true label value of cluster to all points in the cluster for all clusters

new_label = np.zeros(1797)
for i in range(10):
    for j in range(n_samples):
        if assigned_label[j] == i:
            new_label[j] = corrected_label[i]


In [106]:
#print("Final cluster labels:", new_label)
print("Accuracy:",metrics.fowlkes_mallows_score(true_label, new_label))

Accuracy: 0.8321395046705492


In [107]:
confusion = confusion_matrix(true_label, new_label)

confusion[::,9] = -1
print("Confusion_matrix:\n",confusion)

Confusion_matrix:
 [[178   0   0   0   0   0   0   0   0  -1]
 [  0 155  27   0   0   0   0   0   0  -1]
 [  0   0 166   0   0   0   0   1  10  -1]
 [  0   0   0 169   0   0   0   1  13  -1]
 [  0   0   0   0 178   0   0   3   0  -1]
 [  0   0   0   2   0 179   1   0   0  -1]
 [  0   0   0   0   0   0 180   0   1  -1]
 [  0   0   0   0   0   0   0 179   0  -1]
 [  0   3   4   1   0   0   0   1 165  -1]
 [  0  20   0 145   0   2   0  11   2  -1]]
